import { CharacterCard } from '@/components/CharacterCard';
import { List } from '@/components/Layout/List'
import { useGetCharacters } from '@/hooks/useGetCharacters'
import { ICharacter } from '@/interfaces/ICharacter';
import { Content } from 'next/font/google';
import Head from 'next/head'
import { useState } from 'react';


export default function Home() {

  const [page, setPage] = useState(1);
  const { data, error, loading } = useGetCharacters(undefined);

  console.log('error', error, 'loading', loading, 'data', data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <List>
          {!error && !loading && data?.characters?.results?.map((character: ICharacter) =>
            <CharacterCard key={character.id}
              imgSrc={character.image}
              name={character.name}
              type={character.species}
              location={character.location.name}
              status={character.status}
            />
          )}
        </List>
    </>
  )
}
